### PR TITLE
PRESSGANG-94 Upgrade Docbook XSL to 1.79.1 and use (X)HTML5 output

### PR DESCRIPTION
**Pull request by gsmet**
- https://issues.jboss.org/browse/PRESSGANG-94
- https://issues.jboss.org/browse/PRESSGANG-95

PR to be updated once version 2.3.10 of maven-jdocbook-plugin is released.

### CODE REVIEW

**Comment by ge0ffrey** [comment]
There are a lot of custom XSL's overwrites. It's strange that they didn't need to be changed much.
Can you verify:
1) That building works offline
2) That pressgant-tools-example's HTML single and PDF output look the same before and after these changes? See https://github.com/pressgang/pressgang-tools/tree/master/pressgang-tools-example

**Comment by ge0ffrey** [comment]
Depends on https://github.com/pressgang/maven-jdocbook-plugin/pull/3

**Comment by gsmet** [comment]
I checked the doc of OGM before and after (PDF and HTML) and it was fine. I'll take a closer look to your examples.

**Comment by gsmet** [comment]
@ge0ffrey you were right, there were a couple of changes in the way the HTML was generated (the most prominent change is the use of `<section>`s, it was not really visible at first sight, that's why I missed it): a couple of updates to the CSS were required.

The only difference left now is that the TOC is based on ul/li instead of dl/dt. From the Docbook release notes, it looks like they think it's more in the HTML5 spirit. I let it that way but there is a configuration knob to tweak it if you really want the previous behavior back. Here is how it looks like now:
pressgang-new-output.

Even with these changes, the output is not completely HTML5 perfect as there is a `<span id="XXX" />` in the callouts when callouts are used. I didn't find a way to fix it (I think we could fix it by using a more recent version of Saxon as they have an HTML5 mode but then we won't be able to use the Docbook Saxon extensions). It's still way better than before and there are no errors left in the W3C validator when we don't use callouts. Note that apart from the validation issues, we had very annoying issues with anchors not leading exactly to the right place due to the fact that their syntax was not right (`<a id="XXX" />`: Firefox for instance considers this as an open tag without a close tag leading to a lot of open anchors). You can easily see the issues we currently have by going to https://docs.jboss.org/hibernate/stable/ogm/reference/en-US/html_single/ with Firefox and use view source.

**Comment by ge0ffrey** [comment]
IIRC, the pressgang styles on programlistings with callouts were always brittle and hardly ever worked. 

At some point: If you copy-pasted a peice of code you got an extra new line between every 2 lines (very annoying for users). The color highlighting was broken. All that was fixed in a recent release, but callout still remained a problem. In drools,optaplanner & jbpm we don't use callouts so we haven't looked for a fix.

**Comment by ge0ffrey** [comment]
So in short, if the it works offline, copy-pasting of programlistings is fine and color highlighting still works, +1 to merge :)

**Comment by gsmet** [comment]
@ge0ffrey check for all your items.

Before merging this one, we need to merge https://github.com/pressgang/maven-jdocbook-plugin/pull/3 and release a new version of maven-jdocbook-plugin so that I can update the PR with a stable release.

Would you mind coordinating the releases? I'll update the PR accordingly.

Thanks!

**Comment by gsmet** [comment]
@ge0ffrey if you don't have the cycles to do it, would you mind adding me to the pressgang team so that I can work on the releases?

Thanks!

**Comment by ge0ffrey** [comment]
Yes, of course :)

**Comment by ge0ffrey** [comment]
sorry, burried under some other priorities atm, giving you access

**Comment by gsmet** [comment]
Thanks!

**Comment by ge0ffrey** [comment]
@gsmet Thank you. If you don't mind merging both PR's and releasing both components (see their readme's, but releasing them is relatively vanilla). Once they're released, let me know the release number and I can check if the optaplanner docs are still the same output wise, which is a good check of backwards compatibility.

**Comment by gsmet** [comment]
@ge0ffrey I'll work on it tomorrow morning. I probably need the JIRA permissions for both projects so that I can close the version and open a new one.

**Comment by ge0ffrey** [comment]
Should should have developer access on jira now too :)
Double check that I added the correct Guillaume Smet pls.

**Comment by gsmet** [comment]
Looks like it was the wrong one :). My JBoss user name is guillaume.smet.

Thanks!

**Pull request merged**
